### ISSUE TITLE
LapDog UI not working

### ISSUE THREAD

**Issue by jkobject** [broadinstitute/lapdog#84]
**Lapdog Version**: (`lapdog --version` or `pip show lapdog`)
0.15.12

**Describe the bug**
After running the command lapdog ui, I received this error:
```
ERROR in ./src/main.js
Module not found: Error: Can't resolve './Components/Pagination.vue' in '/Users/jeremie/anaconda2/envs/py36/lib/python3.6/site-packages/lapdog/vue/src'
 @ ./src/main.js 8:0-53 50:28-38
```
It seems that the reference file was not installed.

**To Reproduce**
1. Follow the installation instruction
2. Run LapDog UI

**Screenshots**
"ERROR in ./src/main.js
Module not found: Error: Can't resolve './Components/Pagination.vue' in '/Users/jeremie/anaconda2/envs/py36/lib/python3.6/site-packages/lapdog/vue/src'
 @ ./src/main.js 8:0-53 50:28-38"

**Comment by agraubert** [comment]
Yes, I apologize. There was an issue with how I packaged a new UI component. This has been resolved in version [0.15.13](https://pypi.org/project/lapdog/0.15.13/). Please feel free to comment and reopen the issue if you're still experiencing the problem after updating
